services:
  - type: web
    name: freshminds-telegram
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: APP_URL
        sync: false
      - key: KV_REST_API_URL
        sync: false
      - key: KV_REST_API_TOKEN
        sync: false
      - key: PORT
        value: 3000
